/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Armored Core: Master of Arena)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80011D84u
#define func_80011D84 BootEntry  /* alias */
